examen_2/api/urls.py
from django.urls import path
from api import views



app_name = "api"


urlpatterns = [
    
]

examen_2/core/urls.py
from django.urls import path
from core import views



app_name = "core"


urlpatterns = [
    path('list/grantgoal/', views.ListGrantGoal.as_view(), name="gg_list"),
    path('create/grantgoal/', views.CreateGrantGoal.as_view(), name="gg_create"),
    path('detail/grantgoal/<int:pk>/', views.DetailGrantGoal.as_view(), name="gg_detail"),
    path('update/grantgoal/<int:pk>/', views.UpdateGrantGoal.as_view(), name="gg_update"),
    path('delete/grantgoal/<int:pk>/', views.DeleteGrantGoal.as_view(), name="gg_delete"),
    path('list/partidos/', views.ListaPartidos.as_view(), name="p_list"),
    path('create/partidos/', views.CreatePartidos.as_view(), name="p_create"),
    path('detail/partidos/<int:pk>/', views.DetailPartidos.as_view(), name="p_detail"),
    path('update/partidos/<int:pk>/', views.UpdatePartidos.as_view(), name="p_update"),
    path('delete/partidos/<int:pk>/', views.DeletePartidos.as_view(), name="p_delete"),
    path('list/equipos/', views.ListaEquipos.as_view(), name="e_list"),
    path('create/equipos/', views.CreateEquipos.as_view(), name="e_create"),
    path('detail/equipos/<int:pk>/', views.DetailEquipos.as_view(), name="e_detail"),
    path('update/equipos/<int:pk>/', views.UpdateEquipos.as_view(), name="e_update"),
    path('delete/equipos/<int:pk>/', views.DeleteEquipos.as_view(), name="e_delete"),
    path('list/estadios/', views.ListaEstadios.as_view(), name="es_list"),
    path('create/estadios/', views.CreateEstadios.as_view(), name="es_create"),
    path('detail/estadios/<int:pk>/', views.DetailEstadios.as_view(), name="es_detail"),
    path('update/estadios/<int:pk>/', views.UpdateEstadios.as_view(), name="es_update"),
    path('delete/estadios/<int:pk>/', views.DeleteEstadios.as_view(), name="es_delete"),
    path('list/ciudades/', views.ListaCiudades.as_view(), name="c_list"),
    path('create/ciudades/', views.CreateCiudades.as_view(), name="c_create"),
    path('detail/ciudades/<int:pk>/', views.DetailCiudades.as_view(), name="c_detail"),
    path('update/ciudades/<int:pk>/', views.UpdateCiudades.as_view(), name="c_update"),
    path('delete/ciudades/<int:pk>/', views.DeleteCiudades.as_view(), name="c_delete"),
]

examen_2/cplaest/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include("api.urls")),
    path('core/', include("core.urls")),
    path('', include("home.urls")),
]

examen_2/core/models.py
from django.db import models

from django.contrib.auth.models import User

from datetime import timedelta
from django.db.models.signals import post_save
from django.dispatch import receiver

# Create your models here.

STATE_CHOICES = (
    ('Done', 'DN'),
    ('Doing', 'DG'),
    ('Not Stared', 'NS'),
)

ESTADO_EQUIPOS = (
    ('Activo', 'AC'),
    ('Fuera', 'FU'),
)

ESTADO_PARTIDOS = (
    ('En espera', 'ES'),
    ('Dia del partido', 'DP'),
    ('Finalizado', 'FN'),
)

class GrantGoal(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    gg_title = models.CharField(max_length=128, default="Generic Grant Goal Title")
    description = models.CharField(max_length=256, default="Generic Grant Goal Description")
    timestamp = models.DateField(auto_now_add=True)
    days_duration = models.IntegerField(default=7)
    final_date = models.DateField(auto_now_add=False, auto_now=False, blank=True, null=True)
    status = models.BooleanField(default=True)
    state = models.CharField(max_length=16, choices=STATE_CHOICES)
    sprint = models.IntegerField(default=1)
    slug = models.SlugField(max_length=16)

    def __str__(self):
        return self.gg_title



# ## SIGNALS 
# ### post_save
@receiver(post_save, sender=GrantGoal)
def end_time_grantgoal(sender, instance, **kwargs):
    if instance.final_date is None or instance.final_date=='':
        instance.final_date = instance.timestamp + timedelta(days=instance.days_duration)
        instance.save()

### Partidos ###
class Partidos(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    local = models.CharField(max_length=128, default="Local")
    visitante = models.CharField(max_length=256, default="Visitante")
    estadio = models.CharField(max_length=256, default="Estadio")
    fecha = models.CharField(max_length=128, default="Fecha")
    status = models.BooleanField(default=True)
    estado = models.CharField(max_length=16, choices=ESTADO_PARTIDOS)
    duracion = models.IntegerField(default=90)
    slug = models.SlugField(max_length=16)

    def __str__(self):
        return self.local
    
### equipos ###
class Equipos(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    equipo = models.CharField(max_length=128)
    ciudad = models.CharField(max_length=256)
    ganados = models.IntegerField(default=0)
    liga = models.CharField(max_length=256)
    perdidos = models.IntegerField(default=0)
    status = models.BooleanField(default=True)
    estado = models.CharField(max_length=16, choices=ESTADO_EQUIPOS)
    slug = models.SlugField(max_length=16)

    def __str__(self):
        return self.equipo

### estadios ###
class Estadios(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    estadio = models.CharField(max_length=128)
    ciudad = models.CharField(max_length=256)
    equipos = models.IntegerField(default=0)
    status = models.BooleanField(default=True)
    slug = models.SlugField(max_length=16)

    def __str__(self):
        return self.estadio
    
### ciudades ###
class Ciudades(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    ciudad = models.CharField(max_length=128)
    equipos = models.CharField(max_length=256)
    status = models.BooleanField(default=True)
    slug = models.SlugField(max_length=16)

    def __str__(self):
        return self.ciudad

examen_2/core/views.py
from django.shortcuts import render

from django.views import generic

from django.urls import reverse_lazy
from .models import GrantGoal
from .models import Partidos
from .models import Equipos
from .models import Estadios
from .models import Ciudades
from .forms import GrantGoalForm, UpdateGrantGoalForm, PartidosForms, UpgradePartidosForms, EquiposForms, UpgradeEquiposForms, EstadiosForms, UpgradeEstadiosForms, CiudadesForms, UpgradeCiudadesForms
# Create your views here.

##### G R A N T G O A L C R U D #####

##Create
class CreateGrantGoal(generic.CreateView):
    template_name = "core/gg_create.html"
    model = GrantGoal
    form_class = GrantGoalForm
    success_url = reverse_lazy("core:gg_list")


## Retrieve
#List GrantGoal
class ListGrantGoal(generic.View):
    template_name = "core/gg_list.html"
    context = {}

    def get(self, request, *args, **kwargs):
        queryset = GrantGoal.objects.filter(status=True)
        self.context = {
            "grant_goals": queryset
        }
        return render(request, self.template_name, self.context)


#Detail
class DetailGrantGoal(generic.DetailView):
    template_name = "core/gg_detail.html"
    model = GrantGoal


#Update
class UpdateGrantGoal(generic.UpdateView):
    template_name = "core/gg_update.html"
    model = GrantGoal
    form_class = UpdateGrantGoalForm
    success_url = reverse_lazy("core:gg_list")


#Delete
class DeleteGrantGoal(generic.DeleteView):
    template_name = "core/gg_delete.html"
    model = GrantGoal
    success_url = reverse_lazy("core:gg_list")

###-----------------partidos-----------------###
### list ###
class ListaPartidos(generic.View):
    template_name = "core/p_list.html"
    context = {}

    def get(self, request, *args, **kwargs):
        queryset = Partidos.objects.filter(status=True)
        self.context = {
            "partidos": queryset
        }
        return render(request, self.template_name, self.context)
    
### create ###
class CreatePartidos(generic.CreateView):
    template_name = "core/p_create.html"
    model = Partidos
    form_class = PartidosForms
    success_url = reverse_lazy("core:p_list")

### detail ###
class DetailPartidos(generic.DetailView):
    template_name = "core/p_detail.html"
    model = Partidos

### update ###
class UpdatePartidos(generic.UpdateView):
    template_name = "core/p_update.html"
    model = Partidos
    form_class = UpgradePartidosForms
    success_url = reverse_lazy("core:p_list")

### delete ###
class DeletePartidos(generic.DeleteView):
    template_name = "core/p_delete.html"
    model = Partidos
    success_url = reverse_lazy("core:p_list")

###-----------------Equipos-----------------###
### list ###
class ListaEquipos(generic.View):
    template_name = "core/e_list.html"
    context = {}

    def get(self, request, *args, **kwargs):
        queryset = Equipos.objects.filter(status=True)
        self.context = {
            "equipos": queryset
        }
        return render(request, self.template_name, self.context)
    
### create ###
class CreateEquipos(generic.CreateView):
    template_name = "core/e_create.html"
    model = Equipos
    form_class = EquiposForms
    success_url = reverse_lazy("core:e_list")

### detail ###
class DetailEquipos(generic.DetailView):
    template_name = "core/e_detail.html"
    model = Equipos

### update ###
class UpdateEquipos(generic.UpdateView):
    template_name = "core/e_update.html"
    model = Equipos
    form_class = UpgradeEquiposForms
    success_url = reverse_lazy("core:e_list")

### delete ###
class DeleteEquipos(generic.DeleteView):
    template_name = "core/e_delete.html"
    model = Equipos
    success_url = reverse_lazy("core:e_list")

###-----------------Estadios-----------------###
### list ###
class ListaEstadios(generic.View):
    template_name = "core/es_list.html"
    context = {}

    def get(self, request, *args, **kwargs):
        queryset = Estadios.objects.filter(status=True)
        self.context = {
            "estadios": queryset
        }
        return render(request, self.template_name, self.context)
    
### create ###
class CreateEstadios(generic.CreateView):
    template_name = "core/es_create.html"
    model = Estadios
    form_class = EstadiosForms
    success_url = reverse_lazy("core:es_list")

### detail ###
class DetailEstadios(generic.DetailView):
    template_name = "core/es_detail.html"
    model = Estadios

### update ###
class UpdateEstadios(generic.UpdateView):
    template_name = "core/es_update.html"
    model = Estadios
    form_class = UpgradeEstadiosForms
    success_url = reverse_lazy("core:es_list")

### delete ###
class DeleteEstadios(generic.DeleteView):
    template_name = "core/es_delete.html"
    model = Estadios
    success_url = reverse_lazy("core:es_list")

###-----------------Ciudades-----------------###
### list ###
class ListaCiudades(generic.View):
    template_name = "core/c_list.html"
    context = {}

    def get(self, request, *args, **kwargs):
        queryset = Estadios.objects.filter(status=True)
        self.context = {
            "ciudades": queryset
        }
        return render(request, self.template_name, self.context)
    
### create ###
class CreateCiudades(generic.CreateView):
    template_name = "core/c_create.html"
    model = Ciudades
    form_class = CiudadesForms
    success_url = reverse_lazy("core:c_list")

### detail ###
class DetailCiudades(generic.DetailView):
    template_name = "core/c_detail.html"
    model = Ciudades

### update ###
class UpdateCiudades(generic.UpdateView):
    template_name = "core/c_update.html"
    model = Ciudades
    form_class = UpgradeCiudadesForms
    success_url = reverse_lazy("core:c_list")

### delete ###
class DeleteCiudades(generic.DeleteView):
    template_name = "core/c_delete.html"
    model = Ciudades
    success_url = reverse_lazy("core:c_list")

examen_2/templates/core/c_list.html
{% extends 'base/base.html' %}

{% block title %} Lista de Ciudades {% endblock title %}

{% block content %}


    <a href="{% url 'core:c_create' %}" class="btn btn-outline-success form-control">Crear nueva ciudad</a>
    <table class="table table-striped table-hover">
        <thead>
            <th>ID</th>
            <th>CIUDAD</th>
            <th>EQUIPOS</th>
            <th>USER</th>
            <th></th>
            <th>ACTIONS</th>
            <th></th>
        </thead>
        <tbody>
            {% for c in ciudades %}
                <tr>
                    <td>{{ c.id }}</td>
                    <td>{{ c.ciudad }}</td>
                    <td>{{ c.equipos }}</td>
                    <td>{{ c.user }}</td>
                    <td><a href="{% url 'core:c_detail' c.id %}" class="btn btn-outline-info"> Detalles </a></td>
                    <td><a href="{% url 'core:c_update' c.id %}" class="btn btn-outline-warning"> Actualizar</a></td>
                    <td><a href="{% url 'core:c_delete' c.id %}" class="btn btn-outline-danger">Borrar</a></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
   
{% endblock content %}

examen_2/templates/core/e_create.html
{% extends "base/base.html" %}

{% block title %}
  Crear nuevo Equipo
{% endblock title %}

{% block content %}
    <form action="" method="post" class="form">
        {% csrf_token %}
        {{ form }}
        <button type="submit" class="btn btn-outline-success">Crear nuevo equipo</button>
        <a href="{% url 'core:e_list' %}" class="btn btn-outline-warning">Cancelar</a>
    </form>
{% endblock content %}

examen_2/templates/core/e_delete.html
{% extends "base/base.html" %}

{% block title %}
  Eliminar equipo
{% endblock title %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        ¿Quieres borrar los datos del Equipo?: {{ object }}?
        <button type="submit" class="btn btn-outline-danger">Borrar</button>
        <a href="{% url 'core:e_list'%}" class="btn btn-outline-warning">Cancelar</a>
    </form>
{% endblock content %}

examen_2/templates/core/e_detail.html
{% extends "base/base.html" %}

{% block title %}
  Detalles del equipo
{% endblock title %}


{% block content %}
<div class="accordion" id="accordionExample">
    <div class="accordion-item">
      <h2 class="accordion-header" id="headingOne">
        <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
            Nombre
        </button>
      </h2>
      <div id="collapseOne" class="accordion-collapse collapse show" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
        <div class="accordion-body">
          <strong>El equipo {{ object.equipo }} son de la ciudad de {{ object.equipo }}</strong>
        </div>
      </div>
    </div>
    <div class="accordion-item">
      <h2 class="accordion-header" id="headingTwo">
        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
          Estadisticas
        </button>
      </h2>
      <div id="collapseTwo" class="accordion-collapse collapse" aria-labelledby="headingTwo" data-bs-parent="#accordionExample">
        <div class="accordion-body">
          <strong> <ul> <li>partidos ganados: {{ object.ganados }} </li> <li> Partidos perdidos: {{ object.perdidos }}</li></ul> </strong> 
        </div>
      </div>
    </div>
    <div class="accordion-item">
      <h2 class="accordion-header" id="headingThree">
        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
          Liga
        </button>
      </h2>
      <div id="collapseThree" class="accordion-collapse collapse" aria-labelledby="headingThree" data-bs-parent="#accordionExample">
        <div class="accordion-body">
          <strong>El equipo participa en la liga {{ object.liga }} </strong>
        </div>
      </div>
    </div>
  </div>
  
  <a href="{% url 'core:e_list' %}">back to list</a>
{% endblock content %}

examen_2/templates/core/e_update.html
{% extends "base/base.html" %}

{% block title %}
  Actualizar partido
{% endblock title %}

{% block content %}
    <form action="" method="post" class="form">
        {% csrf_token %}
        {{ form }}
        <button type="submit" class="btn btn-outline-primary">Actualizar datos</button>
        <a href="{% url 'core:e_list' %}" class="btn btn-outline-warning">Cancel</a>
    </form>
{% endblock content %}

examen_2/templates/core/es_create.html
{% extends "base/base.html" %}

{% block title %}
  Crear nuevo estadio
{% endblock title %}

{% block content %}
    <form action="" method="post" class="form">
        {% csrf_token %}
        {{ form }}
        <button type="submit" class="btn btn-outline-success">Crear nuevo estadio</button>
        <a href="{% url 'core:es_list' %}" class="btn btn-outline-warning">Cancel</a>
    </form>
{% endblock content %}

examen_2/templates/core/es_detail.html
{% extends "base/base.html" %}

{% block title %}
  Detallas de estadios
{% endblock title %}


{% block content %}
<div class="accordion" id="accordionExample">
    <div class="accordion-item">
      <h2 class="accordion-header" id="headingOne">
        <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
            Nombre
        </button>
      </h2>
      <div id="collapseOne" class="accordion-collapse collapse show" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
        <div class="accordion-body">
          <strong>{{ object.estadio }}</strong> <br>
        </div>
      </div>
    </div>
    <div class="accordion-item">
      <h2 class="accordion-header" id="headingTwo">
        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
          Ciudad
        </button>
      </h2>
      <div id="collapseTwo" class="accordion-collapse collapse" aria-labelledby="headingTwo" data-bs-parent="#accordionExample">
        <div class="accordion-body">
          <strong>El estadio {{ object.estadio }} se encuentra en la ciudad de {{ object.ciudad }}</strong>
        </div>
      </div>
    </div>
    <div class="accordion-item">
      <h2 class="accordion-header" id="headingThree">
        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
          Equipos
        </button>
      </h2>
      <div id="collapseThree" class="accordion-collapse collapse" aria-labelledby="headingThree" data-bs-parent="#accordionExample">
        <div class="accordion-body">
          <strong>El estadio {{ object.estadio }} cuenta con un todal de {{ object.equipos }} equipos</strong>
        </div>
      </div>
    </div>
  </div>
  
  <a href="{% url 'core:es_list' %}">back to list</a>
{% endblock content %}

examen_2/templates/core/es_update.html
{% extends "base/base.html" %}

{% block title %}
  Actualizar estadio
{% endblock title %}

{% block content %}
    <form action="" method="post" class="form">
        {% csrf_token %}
        {{ form }}
        <button type="submit" class="btn btn-outline-primary">Actualizar datos</button>
        <a href="{% url 'core:es_list' %}" class="btn btn-outline-warning">Cancel</a>
    </form>
{% endblock content %}

examen_2/templates/core/gg_create.html
{% extends "base/base.html" %}

{% block title %}
  CREATE GRANT GOAL VIEW
{% endblock title %}

{% block content %}
    <form action="" method="post" class="form">
        {% csrf_token %}
        {{ form }}
        <button type="submit" class="btn btn-outline-success">Create GrantGoal</button>
        <a href="{% url 'core:gg_list' %}" class="btn btn-outline-warning">Cancel</a>
    </form>
{% endblock content %}

examen_2/templates/core/gg_list.html
{% extends 'base/base.html' %}

{% block title %} LIST GRANT GOAL VIEW {% endblock title %}

{% block content %}


    <a href="{% url 'core:gg_create' %}" class="btn btn-outline-success form-control">Create a New GrantGoal</a>
    <table class="table table-striped table-hover">
        <thead>
            <th>ID</th>
            <th>GG TITLE</th>
            <th>TIMESTAMP</th>
            <th>DAYS DURATION</th>
            <th>USER</th>
            <th></th>
            <th>ACTIONS</th>
            <th></th>
        </thead>
        <tbody>
            {% for gg in grant_goals %}
                <tr>
                    <td>{{ gg.id }}</td>
                    <td>{{ gg.gg_title }}</td>
                    <td>{{ gg.timestamp }}</td>
                    <td>{{ gg.days_duration }}</td>
                    <td>{{ gg.user }}</td>
                    <td><a href="{% url 'core:gg_detail' gg.id %}" class="btn btn-outline-info"> Detail </a></td>
                    <td><a href="{% url 'core:gg_update' gg.id %}" class="btn btn-outline-warning"> Update</a></td>
                    <td><a href="{% url 'core:gg_delete' gg.id %}" class="btn btn-outline-danger">Delete</a></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
   
{% endblock content %}

examen_2/templates/core/gg_update.html
{% extends "base/base.html" %}

{% block title %}
  UPDATE GRANT GOAL VIEW
{% endblock title %}

{% block content %}
    <form action="" method="post" class="form">
        {% csrf_token %}
        {{ form }}
        <button type="submit" class="btn btn-outline-primary">Update GrantGoal</button>
        <a href="{% url 'core:gg_list' %}" class="btn btn-outline-warning">Cancel</a>
    </form>
{% endblock content %}

examen_2/templates/core/p_create.html
{% extends "base/base.html" %}

{% block title %}
  Crear nuevo partido
{% endblock title %}

{% block content %}
    <form action="" method="post" class="form">
        {% csrf_token %}
        {{ form }}
        <button type="submit" class="btn btn-outline-success">Crear nuevo partido</button>
        <a href="{% url 'core:p_list' %}" class="btn btn-outline-warning">Cancel</a>
    </form>
{% endblock content %}

examen_2/templates/core/p_detail.html
{% extends "base/base.html" %}

{% block title %}
  Detalles del partido
{% endblock title %}


{% block content %}
<div class="accordion" id="accordionExample">
    <div class="accordion-item">
      <h2 class="accordion-header" id="headingOne">
        <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
            {{ object.local }} vs {{ object.visitante }}
        </button>
      </h2>
      <div id="collapseOne" class="accordion-collapse collapse show" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
        <div class="accordion-body">
          <strong>El partido se desarrolla entre los equipos {{ object.local }}  y {{ object.visitante }} .</strong> <br>
        </div>
      </div>
    </div>
    <div class="accordion-item">
      <h2 class="accordion-header" id="headingTwo">
        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
          Fecha del Partido
        </button>
      </h2>
      <div id="collapseTwo" class="accordion-collapse collapse" aria-labelledby="headingTwo" data-bs-parent="#accordionExample">
        <div class="accordion-body">
          <strong>El partido se disputara la fecha del {{ object.fecha }}</strong>
        </div>
      </div>
    </div>
    <div class="accordion-item">
      <h2 class="accordion-header" id="headingThree">
        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
          Ubicacion
        </button>
      </h2>
      <div id="collapseThree" class="accordion-collapse collapse" aria-labelledby="headingThree" data-bs-parent="#accordionExample">
        <div class="accordion-body">
          <strong>El lugar en que se disputara el partido sera en el estadio {{ object.estadio }}</strong>
        </div>
      </div>
    </div>
  </div>
  
  <a href="{% url 'core:p_list' %}">back to list</a>
{% endblock content %}

examen_2/templates/core/p_list.html
{% extends 'base/base.html' %}

{% block title %} Lista de partidos {% endblock title %}

{% block content %}


    <a href="{% url 'core:p_create' %}" class="btn btn-outline-success form-control">Crear nuevo partido</a>
    <table class="table table-striped table-hover">
        <thead>
            <th>ID</th>
            <th>LOCAL</th>
            <th>VISITANTE</th>
            <th>ESTADIO</th>
            <th>FECHA</th>
            <th>USER</th>
            <th></th>
            <th>ACTIONS</th>
            <th></th>
        </thead>
        <tbody>
            {% for p in partidos %}
                <tr>
                    <td>{{ p.id }}</td>
                    <td>{{ p.local }}</td>
                    <td>{{ p.visitante }}</td>
                    <td>{{ p.estadio }}</td>
                    <td>{{ p.fecha }}</td>
                    <td>{{ p.user }}</td>
                    <td><a href="{% url 'core:p_detail' p.id %}" class="btn btn-outline-info"> Detalles </a></td>
                    <td><a href="{% url 'core:p_update' p.id %}" class="btn btn-outline-warning"> Actualizar</a></td>
                    <td><a href="{% url 'core:p_delete' p.id %}" class="btn btn-outline-danger">Borrar</a></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
   
{% endblock content %}