examen_2/api/urls.py
from django.urls import path
from api import views



app_name = "api"


urlpatterns = [
    
]

examen_2/core/urls.py
from django.urls import path
from core import views



app_name = "core"


urlpatterns = [
    path('list/grantgoal/', views.ListGrantGoal.as_view(), name="gg_list"),
    path('create/grantgoal/', views.CreateGrantGoal.as_view(), name="gg_create"),
    path('detail/grantgoal/<int:pk>/', views.DetailGrantGoal.as_view(), name="gg_detail"),
    path('update/grantgoal/<int:pk>/', views.UpdateGrantGoal.as_view(), name="gg_update"),
    path('delete/grantgoal/<int:pk>/', views.DeleteGrantGoal.as_view(), name="gg_delete"),
    path('list/partidos/', views.ListaPartidos.as_view(), name="p_list"),
    path('create/partidos/', views.CreatePartidos.as_view(), name="p_create"),
    path('detail/partidos/<int:pk>/', views.DetailPartidos.as_view(), name="p_detail"),
    path('update/partidos/<int:pk>/', views.UpdatePartidos.as_view(), name="p_update"),
    path('delete/partidos/<int:pk>/', views.DeletePartidos.as_view(), name="p_delete"),
    path('list/equipos/', views.ListaEquipos.as_view(), name="e_list"),
    path('create/equipos/', views.CreateEquipos.as_view(), name="e_create"),
    path('detail/equipos/<int:pk>/', views.DetailEquipos.as_view(), name="e_detail"),
    path('update/equipos/<int:pk>/', views.UpdateEquipos.as_view(), name="e_update"),
    path('delete/equipos/<int:pk>/', views.DeleteEquipos.as_view(), name="e_delete"),
    path('list/estadios/', views.ListaEstadios.as_view(), name="es_list"),
    path('create/estadios/', views.CreateEstadios.as_view(), name="es_create"),
    path('detail/estadios/<int:pk>/', views.DetailEstadios.as_view(), name="es_detail"),
    path('update/estadios/<int:pk>/', views.UpdateEstadios.as_view(), name="es_update"),
    path('delete/estadios/<int:pk>/', views.DeleteEstadios.as_view(), name="es_delete"),
    path('list/ciudades/', views.ListaCiudades.as_view(), name="c_list"),
    path('create/ciudades/', views.CreateCiudades.as_view(), name="c_create"),
    path('detail/ciudades/<int:pk>/', views.DetailCiudades.as_view(), name="c_detail"),
    path('update/ciudades/<int:pk>/', views.UpdateCiudades.as_view(), name="c_update"),
    path('delete/ciudades/<int:pk>/', views.DeleteCiudades.as_view(), name="c_delete"),
]

examen_2/cplaest/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include("api.urls")),
    path('core/', include("core.urls")),
    path('', include("home.urls")),
]

examen_2/home/urls.py
from django.urls import path
from home import views



app_name = "home"


urlpatterns = [
    path('', views.Index.as_view(), name="index"),
    path('about/', views.About.as_view(), name="about"),    
    path('identity/', views.Identity.as_view(), name="identity"),
    path('contact/', views.Contact.as_view(), name="contact"),
]

examen_2/templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col">
              <nav class="navbar navbar-expand-lg bg-body-tertiary">
                <div class="container-fluid">
                  <a class="navbar-brand" href="{% url 'home:index' %}">FNL</a>
                  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                  </button>
                  <div class="collapse navbar-collapse" id="navbarNavDropdown">
                    <ul class="navbar-nav">
                      <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'home:index' %}">Inicio</a>
                      </li>
                      <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'core:p_list' %}">Partidos</a>
                      </li>
                      <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'core:c_list' %}">Ciudades</a>
                      </li>
                      <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'core:e_list' %}">Equipos</a>
                      </li>
                      <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'core:es_list' %}">Estadios</a>
                      </li>
                    </ul>
                  </div>
                </div>
              </nav>
            </div>
        </div>
        <div class="row">
            <div class="col-2">

            </div>
            <div class="col-10">
                {% block content %}
                {% endblock content %}
            </div>
        </div>
        <div class="row">
            <div class="col">
                <!-- Footer -->
                <footer class="bg-light text-center text-lg-start">
                  <!-- Copyright -->
                  <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
                    © 2023 NFL Network by Reyes Canizales Adrian, 
                    <a class="text-dark" href="https://uttijuana.edu.mx/">Universidad Tecnilogica Tijuana</a>
                  </div>
                  <!-- Copyright -->
                </footer>
                <!-- Footer -->    
            </div>
        </div>
    </div>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>